//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Cfdi.Negocio.ConsultaCfdi.Servicio
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Acuse", Namespace = "http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio")]
    public partial class Acuse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoEstatusField;

        private string EsCancelableField;

        private string EstadoField;

        private string EstatusCancelacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEstatus
        {
            get
            {
                return this.CodigoEstatusField;
            }
            set
            {
                this.CodigoEstatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsCancelable
        {
            get
            {
                return this.EsCancelableField;
            }
            set
            {
                this.EsCancelableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstatusCancelacion
        {
            get
            {
                return this.EstatusCancelacionField;
            }
            set
            {
                this.EstatusCancelacionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IConsultaCFDIService")]
public interface IConsultaCFDIService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConsultaCFDIService/Consulta", ReplyAction = "http://tempuri.org/IConsultaCFDIService/ConsultaResponse")]
    Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse Consulta(string expresionImpresa);

    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IConsultaCFDIService/Consulta", ReplyAction = "http://tempuri.org/IConsultaCFDIService/ConsultaResponse")]
    System.IAsyncResult BeginConsulta(string expresionImpresa, System.AsyncCallback callback, object asyncState);

    Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse EndConsulta(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IConsultaCFDIServiceChannel : IConsultaCFDIService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    public ConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    public Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ConsultaCFDIServiceClient : System.ServiceModel.ClientBase<IConsultaCFDIService>, IConsultaCFDIService
{

    private BeginOperationDelegate onBeginConsultaDelegate;

    private EndOperationDelegate onEndConsultaDelegate;

    private System.Threading.SendOrPostCallback onConsultaCompletedDelegate;

    public ConsultaCFDIServiceClient()
    {
    }

    public ConsultaCFDIServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ConsultaCFDIServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ConsultaCFDIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ConsultaCFDIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public event System.EventHandler<ConsultaCompletedEventArgs> ConsultaCompleted;

    public Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse Consulta(string expresionImpresa)
    {
        return base.Channel.Consulta(expresionImpresa);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public System.IAsyncResult BeginConsulta(string expresionImpresa, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginConsulta(expresionImpresa, callback, asyncState);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse EndConsulta(System.IAsyncResult result)
    {
        return base.Channel.EndConsulta(result);
    }

    private System.IAsyncResult OnBeginConsulta(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string expresionImpresa = ((string)(inValues[0]));
        return this.BeginConsulta(expresionImpresa, callback, asyncState);
    }

    private object[] OnEndConsulta(System.IAsyncResult result)
    {
        Sat.Cfdi.Negocio.ConsultaCfdi.Servicio.Acuse retVal = this.EndConsulta(result);
        return new object[] {
                retVal};
    }

    private void OnConsultaCompleted(object state)
    {
        if ((this.ConsultaCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ConsultaCompleted(this, new ConsultaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }

    public void ConsultaAsync(string expresionImpresa)
    {
        this.ConsultaAsync(expresionImpresa, null);
    }

    public void ConsultaAsync(string expresionImpresa, object userState)
    {
        if ((this.onBeginConsultaDelegate == null))
        {
            this.onBeginConsultaDelegate = new BeginOperationDelegate(this.OnBeginConsulta);
        }
        if ((this.onEndConsultaDelegate == null))
        {
            this.onEndConsultaDelegate = new EndOperationDelegate(this.OnEndConsulta);
        }
        if ((this.onConsultaCompletedDelegate == null))
        {
            this.onConsultaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaCompleted);
        }
        base.InvokeAsync(this.onBeginConsultaDelegate, new object[] {
                    expresionImpresa}, this.onEndConsultaDelegate, this.onConsultaCompletedDelegate, userState);
    }
}
